server:
  port: 8081

spring:
  application:
    name: marque
  datasource:
    url: jdbc:h2:mem:marquedb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true  # Change to false if you don’t want Eureka registration

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'

management:
  endpoints:
    web:
      exposure:
        include: '*'
